AppBundle\Entity\Store:
    type: entity
    table: store
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
        enabled:
            type: boolean
            options:
                default: false
        imageName:
            type: string
            nullable: true
            precision: 0
            column: image_name
        website:
            type: string
            nullable: true
        telephone:
            type: phone_number
            nullable: true
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        legalName:
            type: string
            nullable: true
            column: legal_name
        openingHours:
            type: json_array
            nullable: true
            column: opening_hours
        vatID:
            type: string
            nullable: true
            column: vat_id
        additionalProperties:
            type: json_array
            nullable: true
            column: additional_properties
        prefillPickupAddress:
            type: boolean
            column: prefill_pickup_address
        createOrders:
            type: boolean
            column: create_orders
        checkExpression:
            type: string
            nullable: true
            column: check_expression
        smsEnabled:
            type: boolean
            column: sms_enabled
    manyToOne:
        address:
            targetEntity: AppBundle\Entity\Address
            cascade:
                - all
            joinColumns:
                default_address_id:
                    referencedColumnName: id
        stripeAccount:
            targetEntity: AppBundle\Entity\StripeAccount
            joinColumns:
                stripe_account_id:
                    referencedColumnName: id
        pricingRuleSet:
            targetEntity: AppBundle\Entity\Delivery\PricingRuleSet
            cascade:
                - persist
            fetch: LAZY
            joinColumns:
                pricing_rule_set_id:
                    referencedColumnName: id
        timeSlot:
            targetEntity: AppBundle\Entity\TimeSlot
            cascade:
                - persist
            fetch: LAZY
            joinColumns:
                time_slot_id:
                    referencedColumnName: id
        packageSet:
            targetEntity: AppBundle\Entity\PackageSet
            joinColumns:
                package_set_id:
                    referencedColumnName: id
    manyToMany:
        owners:
            targetEntity: AppBundle\Entity\ApiUser
            mappedBy: stores
        addresses:
            targetEntity: AppBundle\Entity\Address
            cascade:
                - persist
            joinTable:
                name: store_address
                joinColumns:
                    -
                        name: store_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: address_id
                        referencedColumnName: id
    oneToMany:
        deliveries:
            targetEntity: AppBundle\Entity\Delivery
            mappedBy: store
            cascade:
                - persist
